// Diccionario de heurísticas y patrones léxicos para detección de IA en Español
// Incluye huellas lingüísticas de OpenAI (ChatGPT), Anthropic (Claude), Google (Gemini)
// y patrones específicos de evaluación educativa / rúbricas generadas con IA (Google Classroom).
const DocenteLensHeuristicsES = {
  // Frases y marcadores recurrentes típicos de LLMs en español
  cliches: [
    // --- Marcadores comunes y OpenAI (ChatGPT) ---
    "en conclusión",
    "en resumen",
    "es fundamental destacar",
    "es importante señalar",
    "vale la pena mencionar",
    "cabe destacar",
    "cabe señalar",
    "juega un papel fundamental",
    "juega un papel crucial",
    "desempeña un papel crucial",
    "desempeña un rol fundamental",
    "a lo largo de la historia",
    "en el mundo actual",
    "hoy en día",
    "en la era digital",
    "en un mundo en constante evolución",
    "un abanico de posibilidades",
    "un sinfín de oportunidades",
    "un sinfín de posibilidades",
    "profundizar en",
    "un tapiz de",
    "un testimonio de",
    "no se puede subestimar",
    "a medida que avanzamos",
    "un futuro prometedor",
    "sin lugar a dudas",
    "en última instancia",
    "un equilibrio delicado",
    "un viaje transformador",
    "un faro de esperanza",
    "marca un antes y un después",
    "un hito significativo",
    "aspectos multifacéticos",
    "de vital importancia",
    "es menester recordar",
    "en resumidas cuentas",
    "a modo de conclusión",
    "de manera integral",
    "como piedra angular",
    "forjar un camino",

    // --- Marcadores y giros característicos de Anthropic (Claude) ---
    "ciertamente",
    "vale la pena considerar",
    "desde una perspectiva",
    "un matiz importante",
    "es preciso distinguir",
    "conviene subrayar",
    "en este sentido",
    "podemos observar que",
    "resulta interesante notar",
    "resulta interesante destacar",
    "resulta interesante observar",
    "resulta interesante señalar",
    "resulta interesante considerar",
    "resulta interesante",
    "optimiza significativamente",
    "en relación con la tarea",
    "en relación con el",
    "en relación con la",
    "conviene puntualizar",
    "es importante matizar",
    "en términos generales",
    "si bien es cierto que",
    "un aspecto crucial a diferenciar",
    "examinemos con detalle",
    "desde otro punto de vista",
    "cabe reflexionar",
    "por una parte",
    "por otra parte",
    "en rigor",
    "una aproximación reflexiva",
    "cabe acotar",
    "una distinción fundamental",
    "conviene tener presente",
    "es relevante señalar que",
    "es menester",
    "cabe advertir",
    "discernir entre",
    "articulación entre",
    "comprensión holística",
    "teoría y praxis",
    "rigor metodológico",
    "fascinante mundo",
    "en el fascinante mundo",
    "es crucial comprender",

    // --- Marcadores y estructuras características de Google (Gemini) ---
    "en pocas palabras",
    "a continuación te presento",
    "resumen conciso",
    "como resumen conciso",
    "conceptos esenciales",
    "los aspectos principales",
    "aspectos principales a tener en cuenta",
    "para sintetizar",
    "puntos clave a tener en cuenta",
    "puntos clave",
    "en definitiva",
    "de forma práctica",
    "en términos prácticos",
    "veamos paso a paso",
    "de manera directa",
    "ideas clave",
    "aquí tienes un desglose",
    "a grandes rasgos",
    "de un vistazo",
    "claves para entender",
    "a modo de síntesis",
    "principales conclusiones",

    // --- Guías didácticas, explicaciones conceptuales y proyectos escolares de IA ---
    "esta guía detalla",
    "componentes esenciales",
    "características clave",
    "comprender su función",
    "tomar las mejores decisiones",
    "perfil de usuario",
    "cada perfil de usuario",
    "es el cerebro del",
    "se encarga de procesar todas las instrucciones",
    "es ideal para procesos que requieren",
    "presta atención a esto",
    "¡presta atención a esto!",
    "imagina que estás",
    "¿en qué casos es clave?",
    "en qué casos es clave",
    "es especialmente crítica en",
    "es especialmente crítico en",
    "altos y estables",
    "lo que elimina los",
    "más núcleos significan mayor",

    // --- Consignas de Tareas y Proyectos Escolares de IA (Google Classroom / OpenAI) ---
    "primer gran reto práctico",
    "reto práctico del curso",
    "primer gran reto",
    "os convertiréis en",
    "asumiréis el rol de",
    "actuaréis como",
    "vuestra misión será",
    "tendréis que diseñar",
    "tendréis que elaborar",
    "tendréis que desarrollar",
    "setup informático completo ideal",
    "setup informático",
    "diferentes perfiles de usuario",
    "presupuestos reales y ajustados",
    "presupuestos reales",
    "se realiza de forma individual",
    "se realizará de forma individual",
    "nota final de esta evaluación",
    "de la nota final",
    "documentos clave adjuntos",
    "documentos clave",
    "documento donde debéis registrar",
    "justificar técnicamente por qué",
    "justificar técnicamente",
    "límites de presupuesto y las reglas",
    "leedlo atentamente antes de",
    "contiene todas las instrucciones",
    "habéis tomado esa decisión",

    // --- Marcadores de Rúbricas y Evaluación Educativa (Classroom / Tareas) ---
    "mide exactamente",
    "no realiza la entrega",
    "no realiza el corte",
    "no realiza el",
    "no realiza la",
    "no realiza",
    "dimensiones de la madera",
    "corte a inglete a 45º",
    "corte a inglete",
    "ángulo de 45º",
    "monta tu propio ordenador",
    "monta tu propio",
    "asesores tecnológicos",
    "guía del proyecto",
    "plantilla de presupuestos",
    "encontraréis dos documentos clave",
    "presentan ligeras desviaciones",
    "presenta ligeras desviaciones",
    "ligeras desviaciones",
    "difiere bastante de",
    "difiere bastante",
    "difiere significativamente de",
    "recto, preciso y limpio",
    "preciso y limpio",
    "presenta irregularidades",
    "muestra irregularidades",
    "pequeñas irregularidades",
    "no respeta el ángulo",
    "no respeta el",
    "no respeta las especificaciones",
    "no cumple con los requisitos",
    "cumple parcialmente con",
    "cumple parcialmente",
    "cumple con la mayoría de",
    "cumple en su totalidad",
    "muestra una curvatura uniforme",
    "curvatura uniforme",
    "no está redondeada",
    "bien definida",
    "muestra un acabado",
    "con precisión y destreza",
    "de manera adecuada y precisa",
    "evidencia un dominio",
    "evidencia dificultades",
    "sin errores aparentes",
    "con escasa precisión",
    "siguiendo las especificaciones",
    "según lo solicitado",
    "según lo especificado",
    "notable / sobresaliente",
    "suficiente / bien",
    "sin hacer",
    "criterios de evaluación",
    "escala de valoración",
    "desempeño esperado",
    "nivel de logro"
  ],

  // Palabras individuales con sobre-representación estadística en texto generado por IA
  overusedWords: [
    // OpenAI / General
    "fundamental",
    "crucial",
    "integral",
    "multifacético",
    "trascendental",
    "inherente",
    "intrínseco",
    "enriquecedor",
    "catalizador",
    "resiliencia",
    "paradigma",
    "sinergia",
    "holístico",
    "emblemático",
    "faro",
    "tapiz",
    "omnipresente",
    "perenne",

    // Anthropic (Claude)
    "matiz",
    "matizada",
    "matizado",
    "perspectiva",
    "distinción",
    "reflexión",
    "ponderar",
    "rigor",
    "equidad",
    "proporcionalidad",
    "diferenciar",
    "puntualizar",

    // Google (Gemini)
    "desglose",
    "conciso",
    "esencial",
    "síntesis",
    "sintetizar",
    "práctico",
    "panorámica",
    "cúbits",
    "cúbit",

    // Rúbricas y formatos escolares
    "desviaciones",
    "irregularidades",
    "parcialmente",
    "requeridos",
    "especificaciones"
  ],

  // Patrones estructurales típicos (expresiones regulares sin /g para evitar bugs de statefulness en .test())
  patterns: [
    // Introducciones formulaicas
    /^(en primer lugar|por un lado|para comenzar|es necesario destacar|ciertamente|vale la pena considerar|a continuación te presento)[,:]/i,
    // Conclusiones formulaicas
    /^(en conclusión|en resumen|en síntesis|para finalizar|a modo de cierre|en definitiva|en pocas palabras)[,:]/i,
    // Estructuras de lista con negrita típicas: **Concepto:** Explicación
    /\*\*[^*]+\*\*:\s+/,
    // Viñetas con negrita típicas de Gemini / resúmenes
    /^[\*\-]\s+\*\*[^*]+\*\*/m,
    // Listas con viñeta unicode o estándar y definición estructurada: • Concepto: Explicación
    /^[•\-\*]\s+[A-ZÁÉÍÓÚ][^:\n]{2,55}:\s+/m,
    // Auto-pregunta y respuesta retórica explicativa típica de LLMs didácticos (ej: "¿Qué es? Es...", "¿En qué casos es clave? Es...")
    /(¿(?:qué es|cómo funciona|por qué es importante|en qué casos es clave|para qué sirve|cuál es su función)\?)\s*(?:es|se encarga|funciona|porque|sirve|permite|resulta|consiste)/i,
    // Analogías didácticas y llamadas de atención estructuradas de IA
    /(imagina que|piensa en esto como|a modo de analogía|es como si|¡?presta atención a esto!?)/i,
    // Escala de niveles de rúbrica educativa (Notable / Sobresaliente, Suficiente / Bien, etc.)
    /\b(notable\s*\/\s*sobresaliente|suficiente\s*\/\s*bien|insuficiente|sin hacer)\b/i,
    // Escala secuencial de puntos en rúbrica (ej: 10 puntos ... 7 puntos ... 4 puntos)
    /\b\d+\s*puntos?\b[\s\S]{5,120}\b\d+\s*puntos?\b/i,
    // Gradación sintáctica típica de rúbricas LLM
    /\b(ligeras desviaciones|difiere bastante|recto, preciso y limpio|presenta irregularidades|no respeta el|cumple parcialmente)\b/i,
    // Asignación de rol pedagógico / role-play típico de prompts educativos en IA
    /\b(os convertiréis en|asumiréis el rol de|actuaréis como|vuestra misión será|tendréis que diseñar|tendréis que elaborar)\b/i,
    // Declaración de recursos adjuntos generados por LLM: Nombre del Recurso (Tipo):
    /[A-ZÁÉÍÓÚ][\w\s]+\((?:Documento|Hoja de Cálculo|Presentación|Formulario|PDF|Plantilla|Rúbrica|Guía)\):/i,
    // Porcentajes y ponderaciones formales de evaluación escolar en LLMs
    /\brepresenta el \d+%(?: de la nota final)?\b/i,
    // Solicitud formulaica de justificación técnica
    /\bjustificar técnicamente por qué\b/i
  ]
};

if (typeof module !== "undefined" && module.exports) {
  module.exports = DocenteLensHeuristicsES;
}
